Updates to run in Docker

diff --git a/prime-router/prime b/prime-router/prime
--- a/prime-router/prime
+++ b/prime-router/prime
@@ -12,15 +12,28 @@
 
 set -e
 version=0.1-SNAPSHOT
-fat_jar=build/libs/prime-router-$version.jar
-lib_dir="build/libs"
-fat_jar_name=prime-router-$version-jar-with-dependencies.jar
+fat_jar_name=prime-router-$version-all.jar
 slim_jar_name=prime-router-$version.jar
-lib_name=build/azure-functions/prime-data-hub-router/lib
+lib_name=azure-functions/prime-data-hub-router/lib
+lib_dir=build/libs
 
 # find the jar
-if [ -f $fat_jar ]; then
-  jar=$fat_jar
+if [ -f $fat_jar_name ]; then
+  jar=$fat_jar_name
+elif [ -f $lib_dir/$fat_jar_name ]; then
+  jar=$lib_dir/$fat_jar_name
+elif [ -f $slim_jar_name ]; then
+  jar=$slim_jar_name
+  if [ ! -d $lib_name ]; then
+    echo "Could not find a $lib_name directory"
+    exit 1
+  fi
+elif [ -f $lib_dir/$slim_jar_name ]; then
+  jar=$lib_dir/$slim_jar_name
+  if [ ! -d build/$lib_name ]; then
+    echo "Could not find a target/$lib_name directory"
+    exit 1
+  fi
 else
   echo "Could not find a prime-data-hub-router*.jar file"
   exit 1
