delete-untaged-container-images-from-ACR

diff --git a/.github/workflows/cleanup_old_images.yaml b/.github/workflows/cleanup_old_images.yaml
--- a/.github/workflows/cleanup_old_images.yaml
+++ b/.github/workflows/cleanup_old_images.yaml
@@ -75,14 +75,36 @@ jobs:
         # resulting in an orphaned (or "dangling") image. 
         # The previously pushed image's manifest--and its layer data--remains in the registry.
         # They still need to be removed
+      - name: List image manifests in Test env
+        id: list-test-untaged-images
+        run: |
+          az acr login --name pdhtestcontainerregistry
+          az acr repository show-manifests --name pdhtestcontainerregistry --repository pdhtest --orderby time_asc --output tsv --query "[*].{Digest:digest}" | head -n -4 > test-untaged-images.txt
 
-      - name: List untagged images in Staging env
+      - name: Delete image manifest in test env
+        env:
+          TEST_UNTAGED_FILE: test-untaged-images.txt  
+        run: |
+          if [ -e "$TEST_UNTAGED_FILE" ]; then
+            while IFS= read -r manifest_id; do
+                az acr repository delete --name pdhtestcontainerregistry --image pdhtest@$manifest_id --yes
+                if [ $? -eq 0 ]; then
+                    echo "Deleted image: pdhtest:$manifest_id"
+                else
+                    echo "Failed to delete image: pdhtest:$manifest_id"
+                fi
+            done < "$TEST_UNTAGED_FILE"
+              else
+                echo "File not found: $TEST_UNTAGED_FILE"
+          fi
+
+      - name: List image manifests in Staging env
         id: list-stg-untaged-images
         run: |
           az acr login --name pdhstagingcontainerregistry
-          az acr repository show-manifests --name pdhstagingcontainerregistry --repository pdhstaging --orderby time_asc --output tsv --query "[*].{Digest:digest}" | head -n -3 > stg-untaged-images.txt
+          az acr repository show-manifests --name pdhstagingcontainerregistry --repository pdhstaging --orderby time_asc --output tsv --query "[*].{Digest:digest}" | head -n -4 > stg-untaged-images.txt
 
-      - name: Delete untagged images in Staging env
+      - name: Delete image manifest in Staging env
         env:
           STG_UNTAGED_FILE: stg-untaged-images.txt  
         run: |
