add missing quote

diff --git a/.github/workflows/frontend_ci.yml b/.github/workflows/frontend_ci.yml
--- a/.github/workflows/frontend_ci.yml
+++ b/.github/workflows/frontend_ci.yml
@@ -18,6 +18,7 @@ env:
   TEST_SENDER_PASSWORD: ${{ secrets.TEST_SENDER_PASSWORD }}
   TEST_RECEIVER_USERNAME: ${{ secrets.TEST_RECEIVER_USERNAME }}
   TEST_RECEIVER_PASSWORD: ${{ secrets.TEST_RECEIVER_PASSWORD }}
+  LOCAL_SITEMAP_URL: "http://localhost:3000/sitemap.xml"
 
 jobs:
   pre-job:
@@ -78,8 +79,8 @@ jobs:
           sleep 5  # Wait for the server to start up
           echo 
           echo "Checking for sitemap on localhost:3000"
-          if ! curl -s http://localhost:3000/sitemap.xml; then
-            echo ❌ Server failed to start or sitemap not present"
+          if ! curl -s ${{ env.LOCAL_SITEMAP_URL }}; then
+            echo "❌ Server failed to start or sitemap not present"
             exit 1
           else
             echo "✅ Server started successfully"
@@ -96,7 +97,7 @@ jobs:
 
       - name: Run Pa11y Check # Pa11y is configured in frontend-react/.pa11yci
         run: |
-          SITEMAP_URL="http://localhost:3000/sitemap.xml"
+          SITEMAP_URL="${{ env.LOCAL_SITEMAP_URL }}"
           echo "Sitemap URL: $SITEMAP_URL"
 
           echo "Checking Pa11y is installed and accessible"
