switching to Pa11y from Pa11y-CI

diff --git a/.github/workflows/frontend_ci.yml b/.github/workflows/frontend_ci.yml
--- a/.github/workflows/frontend_ci.yml
+++ b/.github/workflows/frontend_ci.yml
@@ -79,49 +79,76 @@ jobs:
           echo 
           echo "Checking for sitemap on localhost:3000"
           if ! curl -s http://localhost:3000/sitemap.xml; then
-            echo "Server failed to start or sitemap not accessible"
+            echo ❌ Server failed to start or sitemap not present"
             exit 1
           else
-            echo "Server started successfully"
+            echo "✅ Server started successfully"
           fi
 
-      - name: Install Pa11y-CI
+      - name: Install Pa11y
         run: |
           echo "Installing google-chrome-stable"
           sudo apt-get update && sudo apt-get install -y google-chrome-stable jq
           echo "Installing Pa11y-CI"
           npm install -g \
-            puppeteer@22.8.2 \
             pa11y@8.0.0 \
-            pa11y-ci@3.1.0 \
-            pa11y-ci-reporter-cli-summary@4.0.0 \
             --no-save
 
       - name: Run Pa11y Check # Pa11y is configured in frontend-react/.pa11yci
         run: |
-          echo "Running Pa11y Check"
-          pa11y-ci --version
+          SITEMAP_URL="http://localhost:3000/sitemap.xml"
+          echo "Sitemap URL: $SITEMAP_URL"
+
+          echo "Checking Pa11y is installed and accessible"
+          pa11y --version
           
           if [ $? -ne 0 ]; then
-            echo "Pa11y-CI installation failed"
+            echo "❌ Pa11y installation failed"
             exit 1
           else
             echo "Running sitemap check - curl on localhost:3000"
-            if ! curl -s http://localhost:3000/sitemap.xml; then
-              echo "Server failed to start or sitemap not accessible"
+
+            if ! curl -s "$SITEMAP_URL"; then
+              echo "❌ Server failed to start or sitemap not accessible"
               exit 1
             else
-              echo "Server appears to be running, starting Pa11y check"
-              # pa11y-ci --reporter=pa11y-ci-reporter-cli-summary --sitemap http://localhost:3000/sitemap.xml \
-              pa11y-ci --config ./.pa11yci --reporter json \
-                --sitemap http://localhost:3000/sitemap.xml \
-                --sitemap-find https://reportstream.cdc.gov/ \
-                --sitemap-replace http://localhost:3000/ | jq || exit 0
+              echo "✅ Server appears to be running"
+              echo "Extracting URLs from sitemap"
+            
+              # Download the sitemap.xml content
+              curl -s "$SITEMAP_URL" -o sitemap.xml
+
+              # Check if download was successful
+              if [ ! -s sitemap.xml ]; then
+                echo "❌ Failed to download sitemap or file is empty."
+                exit 1
+              fi
+
+              # Extract URLs and save them to sitemap_urls.txt
+              #Linux grep flags: -P for Perl-compatible regex, -o for only matching part, -P for non-greedy matching
+              grep -oP '(?<=<loc>).*?(?=</loc>)' sitemap.xml > sitemap_urls.txt
+              # OSX 
+              # grep "<loc>" sitemap.xml | sed -E 's/.*<loc>(.*)<\/loc>.*/\1/' > sitemap_urls.txt
+
+
+              # Check if URLs were extracted successfully
+              if [ -s sitemap_urls.txt ]; then
+                echo "✅ URLs extracted successfully:"
+                cat sitemap_urls.txt
+              else
+                echo "❌ No URLs found in sitemap.xml."
+                exit 1
+              fi
+
+              # Clean up
+              rm sitemap.xml sitemap_urls.txt
+              
             fi
           fi
 
       - name: Stop Frontend Server
         run: |
+          echo "Stopping Frontend Server"
           kill $(cat server.pid)
         
   unit_tests:
